settings:
  clusterName: "eks-karpenter-demo"
  clusterEndpoint: "https://02A5631CDEA4261899C4C5FAE80E25B1.gr7.eu-central-1.eks.amazonaws.com"
  aws:
    disableDryRun: true
    defaultInstanceProfile: "eks-karpenter-demo-karpenter-node-role"

controller:
  env:
    - name: AWS_REGION
      value: "eu-central-1"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::724605101814:role/eks-karpenter-demo-karpenter-controller"

